### ISSUE TITLE
failed to start: None of the enabled containerizers (mesos) could create a container for the provided TaskInfo/ExecutorInfo message

### ISSUE THREAD

**Issue by headsling** [lensacom/satyr#41]
I've installed mesos, zookeeper and marathon.  running the future-pool example fails with the error message :

"failed to start: None of the enabled containerizers (mesos) could create a container for the provided TaskInfo/ExecutorInfo message"

note : running any of the mesos included test clients works fine.

Any ideas where my issue is at? 

cheers,

versions below :
marathon                              1.1.1-1.0.472.ubuntu1404
mesos                                 0.28.2-2.0.27.ubuntu1404
zookeeper                             3.4.5+dfsg-1                       
zookeeper-bin                         3.4.5+dfsg-1                     
zookeeperd                            3.4.5+dfsg-1

**Comment by headsling** [comment]
oh .. and satyr version 0.2.0, tried pip installing and installing from git repo.

**Comment by kszucs** [comment]
The Executor You're using runs a docker containerizer by default. Based on the error, only the mesos containerizer is enabled on your mesos-slave.

see:  http://mesos.apache.org/documentation/latest/configuration/
--containerizers=VALUE 
comma-separated list of containerizer implementations to compose in order to provide containerization. Available options are mesos, external, and docker (on Linux). The order the containerizers are specified is the order they are tried. (default: mesos)

You should try with `docker,mesos`

**Comment by headsling** [comment]
Ah! Of course .. I missed that docker was required.  Thanks for this.

Note - the first example has an assert -  

`assert future.result(timeout=5) == 3`

which should read  

`assert future.result(timeout=5) == 15`
